# Generated by Django 2.1 on 2019-10-29 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('body', models.TextField()),
                ('event_time', models.TimeField()),
                ('alert_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
