# Generated by Django 2.1 on 2019-10-28 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('planners', '0002_auto_20191027_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_remind_time',
            new_name='event_alert_time',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='event_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
